title: Dominic Clark
description: University Student & Software Engineer
site_title: 'Dominic Clark'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Bigoni
blog_url: none
email: dominicbigoni@gmail.com
keybase_username: none
twitter_username: DominicBigoni
reddit_username: Dominic Bigoni

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 